# Pre-commit hooks for SANS-webapp
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter with --fix
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
        files: ^(src|tests)/
      # Run the formatter
      - id: ruff-format
        types_or: [python, pyi, jupyter]
        files: ^(src|tests)/